# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tmsg.proto\x12\x05proto\"\x8f\x01\n\x10HandshakeMessage\x12\'\n\x0b\x63lientHello\x18\x02 \x01(\x0b\x32\x12.proto.ClientHello\x12\'\n\x0bserverHello\x18\x03 \x01(\x0b\x32\x12.proto.ServerHello\x12)\n\x0c\x63lientFinish\x18\x04 \x01(\x0b\x32\x13.proto.ClientFinish\"A\n\x0bServerHello\x12\x11\n\tephemeral\x18\x01 \x01(\x0c\x12\x0e\n\x06static\x18\x02 \x01(\x0c\x12\x0f\n\x07payload\x18\x03 \x01(\x0c\"A\n\x0b\x43lientHello\x12\x11\n\tephemeral\x18\x01 \x01(\x0c\x12\x0e\n\x06static\x18\x02 \x01(\x0c\x12\x0f\n\x07payload\x18\x03 \x01(\x0c\"/\n\x0c\x43lientFinish\x12\x0e\n\x06static\x18\x01 \x01(\x0c\x12\x0f\n\x07payload\x18\x02 \x01(\x0c')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'msg_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HANDSHAKEMESSAGE._serialized_start=21
  _HANDSHAKEMESSAGE._serialized_end=164
  _SERVERHELLO._serialized_start=166
  _SERVERHELLO._serialized_end=231
  _CLIENTHELLO._serialized_start=233
  _CLIENTHELLO._serialized_end=298
  _CLIENTFINISH._serialized_start=300
  _CLIENTFINISH._serialized_end=347
# @@protoc_insertion_point(module_scope)
